### ISSUE TITLE
Transition to OrderedDict in dims

### ISSUE THREAD

**Issue by KornelJahn** [wagdav/dimarray#11]
I think exchanging the nested tuples for an OrderedDict can easily be done.
Shall I do it?

We could (i) include an odict.py for python older Python versions <2.7 and (ii) and import it this way:

```
from sys import version_info
if version_info < (2, 7):
    from odict import OrderedDict
else:
    from collections import OrderedDict
```

**Comment by KornelJahn** [comment]
OrderedDicts cannot be indexed as a[0], only with keys. Is that a problem?

**Comment by wagdav** [comment]
Transition to OrderedDict is complete from 742aeb120b6210894f712c9a0be13f11e80c19cf.
