### ISSUE TITLE
Unnecessary _check_dims call in __new__

### ISSUE THREAD

**Issue by KornelJahn** [wagdav/dimarray#17]
Disable _check_dims for DimArray inputs in __new__ as they are supposed to be valid.

**Comment by wagdav** [comment]
Please check on this. I commented out as follows and all the tests fail.

```
def __new__(cls, input_array, dims):
    if isinstance(input_array, DimArray):
        obj = input_array.view(cls)
    else:
        obj = np.asarray(input_array).view(cls)
        obj.dims = OrderedDict(dims)
    #try:
    #    obj._check_dims()
    #except ValueError:
    #    raise ValueError('invalid dimension info given.')
    #return obj
```

**Comment by KornelJahn** [comment]
You should not comment out the last line :)
    return obj
I have a plan, I am going to rework this whole thing so that it becomes more logical.
