### ISSUE TITLE
another dimarray...

### ISSUE THREAD

**Issue by perrette** [wagdav/dimarray#25]
Hey, this is not really an issue but it's the only way I could think of to contact you. Just wanted to let you know that there is another "dimarray" project out there ([github](https://github.com/perrette/dimarray) or [docs](http://dimarray.readthedocs.org)). The common name is quite coincidental, picked up without knowing of the pre-existing dimarray. Funny enough, but after all a natural name for a natural need.

Anyway, both projects share some of the API (e.g. `DimArray` creation), but I let you have a look in the links above if you're interested. In development, but already handy. Cheers.

**Comment by wagdav** [comment]
Hi @perrette,
Thanks for info! You're project is definitely in a much better shape, than mine :) I abandoned this project so I don't think that the coincidental naming would cause any problem.

**Comment by wagdav** [comment]
I added a link to your project: 0f3076e

**Comment by perrette** [comment]
Hi, thanks !
small spelling mistake: Mathé Perett should be Mahé Perrette

**Comment by wagdav** [comment]
Fixed!

**Comment by perrette** [comment]
Almost, just the final e !
But we are already talking about 2nd details ;)
cheers
