### ISSUE TITLE
Ellipsis support in _dims_getitem

### ISSUE THREAD

**Issue by KornelJahn** [wagdav/dimarray#4]
In the following code:

import numpy as np
from dimarray import DimArray
dims = [('a', [0,1,2,3,4,5]), ('b',[0,1,2])]
a = DimArray(np.arange(6*3).reshape((6,3)), dims=dims)
a[..., 0]

should give the same as a[:, 0] but results in a "TypeError: list indices must be integers, not ellipsis" instead.

**Comment by wagdav** [comment]
Solved in commit  e0a64cb8d3b822d62600c8a165b2ba84e0badf53
