### ISSUE TITLE
islice name possibly confusing in _dims_getitem

### ISSUE THREAD

**Issue by KornelJahn** [wagdav/dimarray#5]
Module itertools has an islice iterator, too. Though it is clear that it is not used in the code but another name would be better to avoid possible confusion.

**Comment by wagdav** [comment]
In 6afe2a5fa3e6d2ad8f2232bc61c748fa617623de it is renamed to _rng_, but this is not very good either. Any suggestions?

**Comment by KornelJahn** [comment]
Possible (but I must admit, rather weak) alternatives:
slice_i (the "i-th" element, as "i" is a often used index for an arbitrary element)
a_slice (="a particular" slice)
one_slice, slice1 (again, one particular)

Or transform all names to the "things" and "thing" formalism, so that you get
"for thing in things". The obvious problem is that "slice" is built-in Python type.
But the official recommendation is to use "slice_" in that case (similarly to "lambda_" in optics codes).
